model_config:
  resnet_size: 18
  pretrained: false
  n_classes: 10
  num_channels: 1

training_config:
  learning_rate: 0.001
  max_epochs: 100
  early_stopping: 15
  seed: 42
  batch_size: 512
  wandb_logger: false
