model_config:
  patch_size: 7
  latent_dim: 224
  n_layers: 12
  n_heads: 8
  dropout: 0.1
  input_shape: [1, 28, 28]
  n_classes: 10

training_config:
  learning_rate: 0.001
  max_epochs: 100
  early_stopping: 15
